//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceHistory
    {
        public int HisId { get; set; }
        public System.DateTime HisDateTime { get; set; }
        public bool HisIsPresent { get; set; }
        public int AttId { get; set; }
    
        public virtual Attendance Attendance { get; set; }
    }
}
